language: python

services:
  - postgresql

env:
  global:
    - DATABASE_URL='postgres://postgres:@localhost:5432/healthsites_test'
    - SECRET_KEY='tT\xd7\xb06\xf7\x9b\xff\x0fZL\xca\xca\x11\xefM\xacr\xfb\xdf\xca\x9b'
    - DJANGO_SETTINGS_MODULE=core.settings.test_travis

python:
  - '2.7'

addons:
  postgresql: "9.3"

install:
  - pip install coveralls coverage
  - pip install -r REQUIREMENTS-dev.txt
  - nodeenv -p --node=0.10.31
  - npm -g install yuglify



before_script:
  - psql -c 'create database gis;' -U postgres
  - psql -c 'create extension postgis;' gis -U postgres
  - cd django_project
  - python manage.py collectstatic --noinput --settings=core.settings.dev_travis

script:
  - cd django_project
  - coverage run manage.py test

after_success:
  - coverage report -m
  - coveralls
